[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchorlesson1 = "5zpafbsuiEUrBd97Hca36q9uLkyu8Y47U55qmupuTzvt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
